import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  headerCard: {
    marginHorizontal: 16,
    padding: 20,
    borderRadius: 24,
    overflow: "hidden",
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.15)",
    marginBottom: 16,
  },
  title: {
    fontSize: 26,
    fontWeight: "800",
    color: "#fff",
    letterSpacing: -0.5,
  },
  subtitle: {
    marginTop: 4,
    color: "rgba(255,255,255,0.75)",
    fontSize: 13,
  },
  actionRowContainer: {
    flexDirection: "row",
    marginHorizontal: 16,
    gap: 12,
    marginBottom: 24,
  },
  actionButtonSplit: {
    flex: 1,
    backgroundColor: "#ffffff",
    borderRadius: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 4,
  },
  actionButtonScanVariant: {
    backgroundColor: "#073474", 
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
  },
  actionText: {
    color: "#073474",
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  actionTextScanVariant: {
    color: "#FFFFFF",
  },
  sectionTitle: {
    marginHorizontal: 16,
    marginBottom: 14,
    fontSize: 16,
    fontWeight: "800",
    color: "#fff",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  card: {
    marginHorizontal: 16,
    marginBottom: 12,
    padding: 16,
    borderRadius: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.15)",
    overflow: "hidden",
  },
  cardInfoGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  avatarIconPlaceholder: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.15)",
    justifyContent: "center",
    alignItems: "center",
  },
  name: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 15,
  },
  location: {
    color: "rgba(255,255,255,0.65)",
    marginTop: 2,
    fontSize: 12,
    fontWeight: "500",
  },
  amount: {
    color: "#f9fafa", 
    fontSize: 18,
    fontWeight: "800",
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 16,
  },
  modalCard: {
    width: "100%",
    padding: 22,
    borderRadius: 28,
    backgroundColor: "#FFFFFF", 
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 12,
  },
  modalHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 18,
  },
  modalTitle: {
    fontSize: 19,
    fontWeight: "800",
    color: "#073474",
    letterSpacing: -0.5,
  },
  closeModalCross: {
    padding: 6,
    backgroundColor: "#F3F4F6",
    borderRadius: 12,
  },
  inputContextLabel: {
    fontSize: 10,
    fontWeight: "800",
    color: "#666666",
    marginBottom: 6,
    letterSpacing: 0.5,
  },
  input: {
    backgroundColor: "#F3F4F6",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 14,
    color: "#000000",
    fontSize: 14,
    fontWeight: "600",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  dropdownSelectorTrigger: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#F3F4F6",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    marginBottom: 14,
  },
  dropdownSelectorTriggerActive: {
    borderColor: "#073474",
    borderWidth: 1.5,
  },
  dropdownTriggerText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#999999",
    flex: 1,
    paddingRight: 8,
  },
  dropdownTriggerTextActive: {
    color: "#073474",
    fontWeight: "700",
  },
  dropdownScrollContainer: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    marginBottom: 14,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  dropdownInnerScroll: {
    maxHeight: 150, // Locks container to support crisp scrolling behaviors inside the modal sheet layout
  },
  dropdownInlineOption: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  dropdownInlineOptionSelected: {
    backgroundColor: "rgba(7, 52, 116, 0.04)",
  },
  optionTextBlock: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingRight: 10,
  },
  optionLabelText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#444444",
    flex: 1,
    paddingRight: 8,
  },
  optionLabelTextSelected: {
    color: "#073474",
    fontWeight: "700",
  },
  optionFeeText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#555555",
  },
  cashDueNotificationBanner: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "rgba(7, 52, 116, 0.05)",
    padding: 12,
    borderRadius: 10,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "rgba(7, 52, 116, 0.1)",
  },
  cashBannerLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: "#073474",
  },
  cashBannerValue: {
    fontSize: 16,
    fontWeight: "900",
    color: "#073474",
  },
  modalActions: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 4,
    gap: 10,
  },
  cancelBtn: {
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: "#F3F4F6",
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  saveBtn: {
    paddingVertical: 14,
    borderRadius: 14,
    flex: 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  cancelText: {
    color: "#666666",
    fontWeight: "700",
    fontSize: 14,
  },
  saveText: {
    color: "#073474",
    fontWeight: "900",
    fontSize: 14,
  },
});

export default styles;