import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginHorizontal: 20,
    marginBottom: 28,
  },
  profileMetaBoxRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  profileBadge: {
    padding: 2,
    backgroundColor: "rgba(255,255,255,0.12)",
    borderRadius: 100,
  },
  idContextSpan: {
    justifyContent: "center",
  },
  idLabelHint: {
    fontSize: 9,
    fontWeight: "800",
    color: "rgba(255,255,255,0.5)",
    letterSpacing: 0.5,
  },
  idNumberText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#FFFFFF",
    marginTop: 1,
  },
  notificationBadge: {
    padding: 10,
    backgroundColor: "rgba(255,255,255,0.12)",
    borderRadius: 14,
    position: "relative",
    justifyContent: "center",
    alignItems: "center",
  },
  redIndicatorDot: {
    position: "absolute",
    top: -2,
    right: -2,
    backgroundColor: "#FF3B30",
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 4,
    borderWidth: 1.5,
    borderColor: "#456da5",
  },
  notificationCounterText: {
    color: "#FFFFFF",
    fontSize: 9,
    fontWeight: "900",
    textAlign: "center",
  },
  justifiedGreetingArea: {
    marginHorizontal: 18,
    marginBottom: 12,
  },
  greetingText: {
    fontSize: 26,
    fontWeight: "900",
    color: "#FFFFFF",
    letterSpacing: -0.5,
  },
  dateSubtitle: {
    fontSize: 13,
    color: "rgba(255, 255, 255, 0.7)",
    marginTop: 2,
    fontWeight: "500",
  },
  payoutCard: {
    marginHorizontal: 16,
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 20,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 5,
  },
  payoutTopMeta: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  payoutContextLabel: {
    fontSize: 10,
    fontWeight: "800",
    color: "#073474",
    letterSpacing: 1.2,
  },
  payoutValue: {
    fontSize: 32,
    fontWeight: "900",
    color: "#000000",
    marginTop: 4,
    letterSpacing: -0.5,
  },
  walletIconContainer: {
    backgroundColor: "rgba(7, 52, 116, 0.08)",
    padding: 12,
    borderRadius: 16,
  },
  dividerDashed: {
    borderBottomWidth: 1,
    borderStyle: "dashed",
    borderColor: "rgba(7, 52, 116, 0.15)",
    marginVertical: 14,
  },
  payoutBottomMeta: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  metaSubText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#555555",
  },
  metaHighlightValue: {
    fontSize: 12,
    fontWeight: "800",
    color: "#27AE60",
  },
  targetCard: {
    marginHorizontal: 16,
    borderRadius: 28,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.16)",
    padding: 20,
    overflow: "hidden",
    marginBottom: 20,
  },
  cardSectionLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: "rgba(255,255,255,0.6)",
    textAlign: "center",
    letterSpacing: 1,
    marginBottom: 16,
  },
  arcContainer: {
    alignItems: "center",
    position: "relative",
    height: 120,
  },
  arcTextAbsoluteWrapper: {
    position: "absolute",
    bottom: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  arcPercentage: {
    color: "#FFFFFF",
    fontSize: 44,
    fontWeight: "900",
    letterSpacing: -1,
  },
  arcInnerLabel: {
    color: "#f5f8f7",
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 1,
    marginTop: -2,
  },
  targetLegendGrid: {
    flexDirection: "row",
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.12)",
    marginTop: 12,
    paddingTop: 16,
  },
  legendNode: {
    flex: 1,
    alignItems: "center",
  },
  legendNodeBorderLeft: {
    borderLeftWidth: 1,
    borderLeftColor: "rgba(255,255,255,0.12)",
  },
  legendLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: "rgba(255,255,255,0.5)",
    letterSpacing: 0.5,
  },
  legendValue: {
    fontSize: 18,
    fontWeight: "800",
    color: "#ebf3f1",
    marginTop: 4,
  },
  legendValueNormal: {
    fontSize: 18,
    fontWeight: "800",
    color: "#FFFFFF",
    marginTop: 4,
  },
  actionHeroButton: {
    marginHorizontal: 16,
    backgroundColor: "#eff3f2",
    borderRadius: 18,
    marginBottom: 28,
    shadowColor: "#00FFCC",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 6,
  },
  actionButtonLayoutAlignment: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    paddingVertical: 16,
  },
  actionHeroButtonText: {
    color: "#073474",
    fontSize: 16,
    fontWeight: "900",
    letterSpacing: -0.2,
  },
});

export default styles;